### ISSUE TITLE
How to make bare import external?

### ISSUE THREAD

**Issue by jeiea** [denoland/deno_emit#135]
If I change `testdata/external.ts` as the following, error occurs.
```typescript
// testdata/external.ts
import "node:fs";
import "react";
```

```
external ...
  bundle ...
------- output -------
import "node:fs";
import "react";

----- output end -----
  bundle ... FAILED (10ms)
  transpile ...
------- output -------
import "node:fs";
import "react";

----- output end -----
  transpile ... FAILED (5ms)
external ... FAILED (due to 2 failed steps) (20ms)

 ERRORS 

external ... bundle => ./tests/utils.ts:271:13
error: Error: Unable to output during bundling.
      const ret = new Error(getStringFromWasm0(arg0, arg1));
                  ^
    at __wbg_new_87297f22973157c8 (file:///D:/Repos/clone/2023/09/deno_emit/js/emit.generated.js:486:19)
    at <anonymous> (file:///D:/Repos/clone/2023/09/deno_emit/js/emit_bg.wasm:1:2897227)
    at <anonymous> (file:///D:/Repos/clone/2023/09/deno_emit/js/emit_bg.wasm:1:414817)
    at <anonymous> (file:///D:/Repos/clone/2023/09/deno_emit/js/emit_bg.wasm:1:1534233)
    at <anonymous> (file:///D:/Repos/clone/2023/09/deno_emit/js/emit_bg.wasm:1:2637372)
    at __wbg_adapter_46 (file:///D:/Repos/clone/2023/09/deno_emit/js/emit.generated.js:240:8)
    at real (file:///D:/Repos/clone/2023/09/deno_emit/js/emit.generated.js:225:14)

external ... transpile => ./tests/utils.ts:279:13
error: Error: Relative import path "react" not prefixed with / or ./ or ../
      const ret = new Error(getStringFromWasm0(arg0, arg1));
                  ^
    at __wbg_new_87297f22973157c8 (file:///D:/Repos/clone/2023/09/deno_emit/js/emit.generated.js:486:19)
    at <anonymous> (file:///D:/Repos/clone/2023/09/deno_emit/js/emit_bg.wasm:1:2897227)
    at <anonymous> (file:///D:/Repos/clone/2023/09/deno_emit/js/emit_bg.wasm:1:356706)
    at <anonymous> (file:///D:/Repos/clone/2023/09/deno_emit/js/emit_bg.wasm:1:1534233)
    at <anonymous> (file:///D:/Repos/clone/2023/09/deno_emit/js/emit_bg.wasm:1:2637372)
    at __wbg_adapter_46 (file:///D:/Repos/clone/2023/09/deno_emit/js/emit.generated.js:240:8)
    at real (file:///D:/Repos/clone/2023/09/deno_emit/js/emit.generated.js:225:14)

 FAILURES 
```

It seems this is intended according to [this](https://github.com/denoland/deno_emit/blob/cff602f7c8331c86d02bede9d00c0e386c971343/tests/common_test.ts#L132-L147), but then how to make "react" module external?

**Comment by yacinehmito** [comment]
You can use the `load` function in the option. It accepts a specifier and you can return `{ kind: "external", specifier }` so that it never gets bundled.

Example from my own project where I want to treat all node builtin modules as externals:

```typescript
import { createCache } from "https://deno.land/x/deno_cache@0.5.2/mod.ts";
import { bundle as denoBundle } from "https://deno.land/x/emit@0.27.0/mod.ts";

export async function bundle(path: string): Promise<string> {
  const loadCache = createCache();
  const { code } = await denoBundle(path, {
    async load(specifier) {
      if (specifier.startsWith("node:")) {
        return { kind: "external", specifier };
      }
      return loadCache.load(specifier);
    },
  });
  return code;
}
```

**Comment by jeiea** [comment]
I think it is already using [load](https://github.com/denoland/deno_emit/blob/178a8a7f9fa8ba81a8a30f7e54d8c3b62f620555/tests/common_test.ts#L183-L189).

**Comment by yacinehmito** [comment]
This is a test. There is a default implementation of load indeed, but it doesn't handle node specifiers. Have you tried the solution I suggested?

**Comment by jeiea** [comment]
I asked here because I discovered that behavior. I'll close this because I choose other workaround and lose interest about this.
