### ISSUE TITLE
Unable to import module pre 1.22

### ISSUE THREAD

**Issue by johnspurlock** [denoland/deno_emit#24]
Upgrade Deno version to 1.21.3

```ts
import { bundle } from 'https://deno.land/x/emit@0.0.1/mod.ts';
```

fails (see below)

It should import successfully, even on downlevel versions where it may not be used at runtime.

```
error: TS2741 [ERROR]: Property 'imports' is missing in type '{}' but required in type 'BundleOptions'.
  options: BundleOptions = {},
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/emit@0.0.1/mod.ts:60:3

    'imports' is declared here.
      imports: Record<string, string[]>;
      ~~~~~~~
        at https://deno.land/x/emit@0.0.1/mod.ts:28:3

TS2322 [ERROR]: Type '(arg1: string, arg2: boolean) => Promise<{ kind: string; specifier?: string | undefined; headers?: Record<string, string> | undefined; content?: string | undefined; }>' is not assignable to type '(specifier: string, isDynamic: boolean) => Promise<LoadResponse | undefined>'.
  Type 'Promise<{ kind: string; specifier?: string | undefined; headers?: Record<string, string> | undefined; content?: string | undefined; }>' is not assignable to type 'Promise<LoadResponse | undefined>'.
    Type '{ kind: string; specifier?: string | undefined; headers?: Record<string, string> | undefined; content?: string | undefined; }' is not assignable to type 'LoadResponse'.
      Types of property 'specifier' are incompatible.
        Type 'string | undefined' is not assignable to type 'string'.
          Type 'undefined' is not assignable to type 'string'.
    bundleLoad = async (arg1, arg2) => {
    ~~~~~~~~~~
    at https://deno.land/x/emit@0.0.1/mod.ts:78:5

TS2554 [ERROR]: Expected 1 arguments, but got 2.
      const r = await cache.load(arg1, arg2);
                                       ~~~~
    at https://deno.land/x/emit@0.0.1/mod.ts:79:40

TS2554 [ERROR]: Expected 5 arguments, but got 4.
  return jsBundle(root, bundleLoad, imports, undefined);
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/emit@0.0.1/mod.ts:83:10

    An argument for 'maybe_compiler_options' was not provided.
      maybe_compiler_options,
      ~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/x/emit@0.0.1/lib/deno_emit.generated.js:167:3

TS7006 [ERROR]: Parameter 'arg1' implicitly has an 'any' type.
  const emitLoad = async (arg1, arg2) => {
                          ~~~~
    at https://deno.land/x/emit@0.0.1/mod.ts:101:27

TS7006 [ERROR]: Parameter 'arg2' implicitly has an 'any' type.
  const emitLoad = async (arg1, arg2) => {
                                ~~~~
    at https://deno.land/x/emit@0.0.1/mod.ts:101:33

TS2554 [ERROR]: Expected 1 arguments, but got 2.
    const r = await cache.load(arg1, arg2);
                                     ~~~~
    at https://deno.land/x/emit@0.0.1/mod.ts:102:38

Found 7 errors.
```

**Comment by kitsonk** [comment]
Closed in #15
